# Generated by Django 2.2 on 2019-12-13 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('University', '0002_auto_20191213_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='userEmail',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='userPhone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CollegeRepr',
        ),
    ]
