# Generated by Django 2.2 on 2019-12-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0003_auto_20191213_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignmentID', models.CharField(max_length=100)),
                ('totalPair', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Shipped', 'Shipped'), ('On Route', 'On Route'), ('Delivered', 'Delivered')], default='Shipped', max_length=20)),
                ('totalCommission', models.IntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.University')),
            ],
        ),
        migrations.CreateModel(
            name='representativePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushMoney', models.IntegerField()),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.consignment')),
            ],
        ),
    ]
