# Generated by Django 2.2 on 2019-12-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0004_consignment_representativepush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='consignmentID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
