# Generated by Django 2.2 on 2019-12-14 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0005_auto_20191214_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
