# Generated by Django 2.2 on 2019-12-17 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0007_consignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='representativepush',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
