# Generated by Django 2.2 on 2019-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0008_representativepush_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='totalPaid',
            field=models.IntegerField(default=0),
        ),
    ]
