# Generated by Django 2.2 on 2019-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0009_consignment_totalpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='representativepush',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Approved', 'Approved')], default='Initiated', max_length=20),
        ),
    ]
