# Generated by Django 2.2 on 2019-12-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0011_auto_20191219_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='user',
        ),
        migrations.RemoveField(
            model_name='university',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='university',
            name='userPhone',
        ),
    ]
