# Generated by Django 2.2 on 2019-12-20 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('University', '0012_auto_20191220_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNo', models.CharField(max_length=15, verbose_name='Contact No')),
                ('College', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
