# Generated by Django 2.2 on 2019-12-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0013_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='user',
        ),
        migrations.AddField(
            model_name='consignment',
            name='representative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='University.representative'),
            preserve_default=False,
        ),
    ]
