# Generated by Django 2.2 on 2019-12-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0014_auto_20191220_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('On Route', 'On Route'), ('Delivered', 'Delivered'), ('Processing', 'Processing')], default='Shipped', max_length=20),
        ),
    ]
