# Generated by Django 2.2 on 2019-12-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0015_auto_20191220_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='localAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='University.University')),
            ],
        ),
    ]
